#Taxonomy of the samples to be processed, possible are Eukarya, Bacteria, Archea
taxonomy: "Eukarya"
#Adapter sequence used
adapter: ""
methods: methods.tsv
conditions: conditions.tsv
samples: samples.tsv
